'use client';

import Link from 'next/link';
import { useAuth } from '@/lib/auth-context';
import styles from './page.module.css';

export default function HomePage() {
  const { user } = useAuth();

  return (
    <div className={styles.hero}>
      {/* Ambient orbs */}
      <div className={styles.orbPrimary} />
      <div className={styles.orbAccent} />

      <div className={`container ${styles.heroContent}`}>
        <div className={styles.badge}>
          <span className={styles.badgeDot} />
          AI-Powered Comprehension Engine
        </div>

        <h1 className={styles.title}>
          Master Any Subject with
          <br />
          <span className="text-gradient">Intelligent Quizzes</span>
        </h1>

        <p className={styles.subtitle}>
          Paste your study material, and Kai generates 20 MCQs + short-answer questions,
          scores your responses with AI, and tracks your Comprehension Index over time.
        </p>

        <div className={styles.cta}>
          {user ? (
            <>
              <Link href="/generate" className="btn btn-primary btn-lg">
                Generate Quiz ⚡
              </Link>
              <Link href="/dashboard" className="btn btn-secondary btn-lg">
                View Dashboard
              </Link>
            </>
          ) : (
            <>
              <Link href="/register" className="btn btn-primary btn-lg">
                Start Free →
              </Link>
              <Link href="/login" className="btn btn-secondary btn-lg">
                Sign In
              </Link>
            </>
          )}
        </div>

        {/* Feature Grid */}
        <div className={styles.features}>
          <div className={styles.featureCard}>
            <div className={styles.featureIcon}>🧠</div>
            <h3>AI Quiz Generation</h3>
            <p>Paste any study material and get 20 MCQs + 2 short-answer questions instantly</p>
          </div>
          <div className={styles.featureCard}>
            <div className={styles.featureIcon}>📊</div>
            <h3>Comprehension Index</h3>
            <p>Track your understanding with a scientific formula combining accuracy and improvement</p>
          </div>
          <div className={styles.featureCard}>
            <div className={styles.featureIcon}>🎯</div>
            <h3>AI Answer Scoring</h3>
            <p>Short answers scored by AI with detailed strength/weakness feedback</p>
          </div>
          <div className={styles.featureCard}>
            <div className={styles.featureIcon}>📈</div>
            <h3>Progress Tracking</h3>
            <p>Dashboard with history, averages, and improvement metrics across all quizzes</p>
          </div>
        </div>

        {/* How it works */}
        <div className={styles.howItWorks}>
          <h2 className="heading-lg" style={{ textAlign: 'center', marginBottom: '40px' }}>
            How It <span className="text-gradient">Works</span>
          </h2>
          <div className={styles.steps}>
            <div className={styles.step}>
              <div className={styles.stepNumber}>1</div>
              <h4>Upload Content</h4>
              <p>Paste your notes, textbook chapters, or any study material</p>
            </div>
            <div className={styles.stepLine} />
            <div className={styles.step}>
              <div className={styles.stepNumber}>2</div>
              <h4>Take the Quiz</h4>
              <p>Answer 20 MCQs and 2 short-answer questions generated by AI</p>
            </div>
            <div className={styles.stepLine} />
            <div className={styles.step}>
              <div className={styles.stepNumber}>3</div>
              <h4>Get Your Score</h4>
              <p>See your Comprehension Index with detailed breakdowns</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
